### ISSUE TITLE
autoSessionTracking / enableAutoSessionTracking option is ignored, unwanted tracking of users

### ISSUE THREAD

**Issue by jansgescheit** [getsentry/sentry-capacitor#123]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?

- "@capacitor/android": "^3.4.0",
- "@capacitor/cli": "^3.4.0",
- "@capacitor/core": "^3.4.0",
- "@capacitor/ios": "^3.4.0",
- "@ionic/angular": "^6.0.7",
- "@ionic/core": "^6.0.7",
- "@sentry/angular": "^6.11.0",
- "@sentry/capacitor": "^0.4.1",

Tested on iOS, API Request a captured via mitmproxy 

### Steps to Reproduce

- Setup Sentry and set `autoSessionTracking: false` e.g.
```json
{
        dsn: 'https://random-uuid@sentry.io/????',
        environment: 'prod',
        integrations: [new Integrations.BrowserTracing()],
        tracesSampleRate: 1.0,
        release: '1.0.0',
        autoSessionTracking: false,
}
```

- build angular ionic application in production
- sync files with `npx cap sync ios`
- open xcode `npx cap open ios`
- run on a real device
- view network traffic

### Expected Result

there should be no more API calls to `https://sentry.io/api/?/envelope/` on ui clicks

### Actual Result

The `autoSessionTracking` setting is ignored on native builds. If you look at the [source code](https://github.com/getsentry/sentry-capacitor/blob/d1db0026141535201e723d90155f63e7d16a64ee/src/sdk.ts#L83), the option is is overridden with `enableAutoSessionTracking`. However, this option is not described anywhere in the capacitor documentation. 

If I set `enableAutoSessionTracking` option explicitly to false, it still doesn't seem to make any difference and every click is still transmitted to the API, it shouldn't be like that. We do not want to track our users unnecessarily.

**Comment by bruno-garcia** [comment]
`enableAutoSessionTracking` doesn't control requests to the envelope endpoint when a user clicks on elements in the UI.
The "tracking" in the name isn't really about user tracking. It's only sending data that cannot be used to identify a user, and in that data we say whether things are "healthy" or "errored/crashed". This is just to give you stats whether your app is generally functioning OK or if it's buggy.

This data powers the "Release Health" feature, which gives you "crash free rate" over time. So when you make new releases you can see if you're improving the quality of your release.

That said, setting it to `false` should make sure no 'session' payload is sent to Sentry. But other events such as errors and crashes will continue to be sent. To disable those, you'd need to avoid initializing Sentry altogether (since that's the base product: Find out when things break).

We need to investigate if `enableAutoSessionTracking` isn't being passed down to the native SDK

**Comment by jansgescheit** [comment]
Thank you for your explanation @bruno-garcia .

I understood that I can generally deactivate the transmission using `enableAutoSessionTracking = false`. I have not checked the quality of usage data attached there. So my fault.

I'm not primarily interested in whether things are healthy or errored/crashed. I just want to get the errors tracked. How can I achieve this exactly? In our case over ~80% of the requests that our application currently makes go to Sentry. Unfortunately, this is not our understanding of data economy.

**Comment by jansgescheit** [comment]
I slept one night and I have a solution to my (Layer-8) problem 😶‍🌫️ . Remove `integrations: [new Integrations.BrowserTracing()]` in the `init` call. 🤦

**Comment by bruno-garcia** [comment]
Thanks for sharing this use case. It'll likely help others that end up here when searching.
