### ISSUE TITLE
Implement electron platform

### ISSUE THREAD

**Issue by muuvmuuv** [getsentry/sentry-capacitor#172]
There is a package available to use Electron platform together with Capacitor, unfortunately it will log a lot of "Native client not available" errors. Would it be possible or in range of this package to add the electron platform? 

Here is an instruction on how to add electron as a platform for capacitor: https://capacitor-community.github.io/electron/docs/creatingplugins

**Comment by bruno-garcia** [comment]
What would that support look like? `@sentry/electron` bundles the JS SDK just like we do here already. So I assume we'd need to pull some of the code written for electron in https://github.com/getsentry/sentry-electron and share it here? cc @AbhiPrasad @timfish

**Comment by muuvmuuv** [comment]
I guess, at least for Sentry here, it's just like wrapping it, so the capacitor electron platform can use it properly.

Here is an example from SQLite: https://github.com/capacitor-community/sqlite

**Comment by timfish** [comment]
Reading the docs for `@capacitor-community/electron`, once you install it you'll get a `*yourAppDir*/electron/src/index.ts` file added to your project. I haven't had a proper look yet but I'm guessing this is the Electron startup code where you would just start the Electron SDK.

You'll also need to start the Electron SDK in the browser front end and this code will vary from the other platforms. Is there a way for the build to select different JavaScript entry points for each platform?

**Comment by AbhiPrasad** [comment]
Would this need to live in a separate repo? Also there will be complexities in versioning, especially because electron and capacitor can (and will usually) depend on different versions on the base JS SDK.

**Comment by timfish** [comment]
Versioning pain aside, I'm guessing we could:

- add `@sentry/electron` as an optional peer dep
- add some code that `init`s the Electron SDK browser code when targeting that platform
- add `electron` to the `capacitor` key in `package.json` pointing to above entry code

Because Electron has multiple processes we'd need to get users to `init` the SDK in the main process too.

So instructions for users would go:
- Install `@sentry/electron`
- Init the Electron SDK in `*yourAppDir*/electron/src/index.ts`
- Everything worky

But yeah, versioning would be super painful 🤔

**Comment by muuvmuuv** [comment]
A version painless solution would be to just use the web SDK in electron, but I couldn't get that to work (though I thought it would already fall back to web if nothing else declared).
