### ISSUE TITLE
Import Cocoa private hybrid SDK headers directly

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-capacitor#252]
Hybrids SDKs, when using PrivateSentrySDKOnly class, will need to explicitly import <Sentry/PrivateSentrySDKOnly.h> alongside <Sentry/Sentry.h> starting with the next major release. The explicit import can already be added.

see https://github.com/getsentry/team-mobile/issues/66

**Comment by lucas-zimerman** [comment]
> Hybrids SDKs, when using PrivateSentrySDKOnly class, will need to explicitly import <Sentry/PrivateSentrySDKOnly.h> alongside <Sentry/Sentry.h> starting with the next major release. The explicit import can already be added.
> 
> see [getsentry/team-mobile#66](https://github.com/getsentry/team-mobile/issues/66)

Since both Flutter and Capacitor uses Swift to interact with the Native SDK, it might be a good idea to wait for the Flutter SDK to implement this change and then "port" it to Sentry/Capacitor, this will avoid different teams spending time on the same problem.

See https://github.com/getsentry/team-mobile/issues/66#issuecomment-1300304401

**Comment by lucas-zimerman** [comment]
Closed by https://github.com/getsentry/sentry-capacitor/pull/259
