### ISSUE TITLE
Session Replay: Support Generally Available

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-capacitor#319]
This issue will track GA'ing Capacitor support outside of the general browser support.

Known issues:
- [x] https://github.com/getsentry/sentry-capacitor/issues/318
- [x] Update the JS SDK (several fixes [since this](https://github.com/getsentry/sentry-capacitor/blob/main/package.json#L41))

**Comment by lucas-zimerman** [comment]
https://sentry-sdks.sentry.io/replays/7f276477ce1f455f88b79cd2cc572b1a/?project=5522756&query=&referrer=%2Freplays%2F&statsPeriod=1h&yAxis=count%28%29

@bruno-garcia replays on Capacitor on the latest versions are working just fine (except for local images that aren't sent but I think this is an expected behaviour).

Should we close this issue or do we need anything else before closing it?

**Comment by bruno-garcia** [comment]
Great to hear that! Thanks Lucas
