### ISSUE TITLE
Officially support Vue

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-capacitor#41]
Add an example app, and fully test all features.

**Comment by reslear** [comment]
any news?

**Comment by bruno-garcia** [comment]
No plan for this yet. But'd be glad to merge a PR though. It's pretty much doing the same we did for Angular

**Comment by reslear** [comment]
is PR welcome?

**Comment by lucas-zimerman** [comment]
Currently the SDK works with Vue, but an sample app using Vue surely would help alot.

**Comment by iBobik** [comment]
It still make sense to support it.Honza Pobořil💬Signal2. 8. 2023 v 2:11, github-actions[bot] ***@***.***>:﻿
This issue has gone three weeks without activity. In another week, I will close it.
But! If you comment or otherwise update it, I will reset the clock, and if you label it Status: Backlog or Status: In Progress, I will leave it alone ... forever!

"A weed is but an unloved flower." ― Ella Wheeler Wilcox 🥀

**Comment by lucas-zimerman** [comment]
An sample app was tested and it's being validated with github actions build
