### ISSUE TITLE
No events from mobile devices

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry-capacitor#595]
### Environment

"@sentry/angular-ivy": "^7.81.1",
"@sentry/capacitor": "^0.15.1",

> We can't increase angular-ivy to the latest version because it clashes with the capacitor library.

### Steps to Reproduce
```javascript
public async initMobileAppSentry() {
    Sentry.init({
            dsn: 'DSN_KEY',
            release: `RELEASE_NAME`,
            environment: this.environment?.production ? 'production' : 'development',
            tracesSampleRate: this.environment?.production ? 0.1 : 1.0,
            tracePropagationTargets: this.MY_ENDPOINTS,
            replaysSessionSampleRate: 0.1,
            replaysOnErrorSampleRate: 0.5,
            integrations: [
                new Sentry.BrowserTracing({
                    routingInstrumentation: SentryAngular.routingInstrumentation,
                }),
            ],
        },
        SentryAngular.init,
    );
}
```
The library is initialized on startup. The customer is using NGRX, so they dispatch an action when the platform is ready to initialize Sentry. This should happen immediately when the app initializes.

### Expected Result

Sentry receives events from the app from all devices.

### Actual Result

Sentry works great in browsers but doesn't receive any events from mobile devices.
Used both
```javascript
Sentry.captureException("Test Captured Exception");
```
and
```javascript
throw new Error(`Test Thrown Error`);
```
but neither arrive in Sentry.

Debug logs:
[Android log.txt](https://github.com/getsentry/sentry-capacitor/files/14600269/Android.log.txt)
[iOS log.txt](https://github.com/getsentry/sentry-capacitor/files/14600270/iOS.log.txt)

**Comment by lucas-zimerman** [comment]
Hi and thanks for opening this issue!

Firstly ,I would like to recommend using a fixed version of sentry/capacitor and sentry/angular-ivy, that will avoid incompatibility issues, for example:
```
"@sentry/angular-ivy": "7.93.0",
"@sentry/capacitor": "0.16.0",
```
 
With that said, I have tested on a small project with `ngrx` and it seems to be capturing on both browser and mobile. On the other hand I noticed that depending on the code that you're using, (for example `createEffect` from `@ngrx/effects`), if you are using a `catchError` function inside the effect, you'll need to manually call Sentry.CaptureException in order to capture the error.

If the problem still persists when using the fixed versions, would you mind sending another log, but this time with `debug: true` on the initialisation of the SDK? also, does the problem still persists if you set `enableNative: false` inside of the initialisation of the SDK?

**Comment by JackLazenbyZigzag** [comment]
Hi there,

Thanks for getting back to us so quickly on this!

No luck so far.

I've changed the libraries to be static as recommend, and then updated our init as so:

```
public async initMobileAppSentry() {
        Sentry.init(
            {
                dsn: 'https://333f85cd489f1e3ac2bf0b47a7f6e87c@o4506677667168256.ingest.sentry.io/4506677669330944',
                release: `zigzag@${APP_VERSION_NUMBER}`,
                environment: this.environment?.production ? 'production' : 'development',
                tracesSampleRate: this.environment?.production ? 0.1 : 1.0,
                tracePropagationTargets: this.ZIGZAG_ENDPOINTS,
                replaysSessionSampleRate: 0.1,
                replaysOnErrorSampleRate: 0.5,
                enableNative: false,
                debug: true,
            },
        );
        SentryAngular.init({
            integrations: [
                new SentryAngular.BrowserTracing({
                    routingInstrumentation: SentryAngular.routingInstrumentation,
                }),
            ],
        })
    }
```

Have attached logs from Android as requested.

[Android Log 15-03-2024.txt](https://github.com/getsentry/sentry-capacitor/files/14618038/Android.Log.15-03-2024.txt)

**Comment by JackLazenbyZigzag** [comment]
Hi there,

Apologies, we weren't getting events through following these changes as we'd hit our plan limit.

This seems to be working now! Thank you.
