### ISSUE TITLE
Is it safe for production? Does it support both Capacitor 2.x and Capacitor 3.x?

### ISSUE THREAD

**Issue by StErMi** [getsentry/sentry-capacitor#64]
We are developing a Capacitor application in React and we would like to add Sentry support. 

Is this SDK production safe? Does it support both Capacitor 2.x and Capacitor 3.x? (we are using Capacitor 2.x but we are planning to upgrade to 3.x).

Is there something that is missing from the feature list of the Sentry React SDK?

**Comment by Cyral** [comment]
Also interested in the answer - currently have a Capacitor 3 (Ionic) React app and would like to use this. If it isn't ready, then can the regular Sentry React integration be used (since Capacitor is just a web view I think it may be possible)?

**Comment by jennmueng** [comment]
@StErMi You would be able to use this SDK for both Capacitor 2.x and 3.x, although as there are breaking changes on Capacitor 3, to use the SDK with Capacitor 2 you will have to follow [this guide on our docs](https://docs.sentry.io/platforms/javascript/guides/capacitor/troubleshooting/#capacitor-2-on-ios).

@Cyral You should be able to just use this SDK with the React SDK as the "Sibling" SDK instead of the `@sentry/angular` one. We just haven't tested everything out yet so we don't "officially" support it yet. In theory it should work just fine, you can try it out by following our installation guide but replace the steps with:
```bash
yarn add @sentry/capacitor @sentry/react
```
and
```js
import * as Sentry from "@sentry/capacitor";
import * as SentryReact from "@sentry/react";

Sentry.init(
  {
    dsn: "https://examplePublicKey@o0.ingest.sentry.io/0",

    // To set your release and dist versions
    release: "my-project-name@" + process.env.npm_package_version,
    dist: "1"
  },
  // Forward the init method from @sentry/react
  SentryReact.init
);
```

If you run into any issues, you can just run the Sentry Capacitor SDK standalone with 
```js
import * as Sentry from "@sentry/capacitor";

Sentry.init(
  {
    dsn: "https://examplePublicKey@o0.ingest.sentry.io/0",

    // To set your release and dist versions
    release: "my-project-name@" + process.env.npm_package_version,
    dist: "1"
  }
 // no second argument
);
```

**Comment by lucas-zimerman** [comment]
Yes it's ready for production, if you find any issues feel free to open an issue or contact support.
