### ISSUE TITLE
iOS app crashes when exception is captured

### ISSUE THREAD

**Issue by chris-si** [getsentry/sentry-capacitor#687]
### Environment
```
"@capacitor/*": "6.0.0",
"@sentry/capacitor": "^0.18.0",
"@sentry/vue": "^7.114.0",
"vue": "^3.4.31",
```
Tested on
- iPhone 13, iOS 17.5.1
- iPadPro 3rd gen, iPadOS 17.5.1
- XCode Simulator, iOS 17.2

### Steps to Reproduce

1. Clone [this repo](https://github.com/chris-si/capacitor-sentry-test)
2. Install dependencies via `npm install`
3. Rename `.env.sample` to `.env` and add the DSN
4. Run `ionic serve` (it will start the project in a browser) and click the button `Throw error` in the app (it works just fine)
5. Run `ionic cap build ios` to trigger a production build and run the app on an iOS device and click the button

### Expected Result

The app should not crash or hang in any case if an error is thrown and captured by sentry.

### Actual Result

In most of the cases the app will hang and then crash after a short amount of time. In (very) rare cases the app just hangs and is unresponsive and resumes its duties again.

- When tested on the web (via `ionic serve`), it just works fine and the errors are captured without any problems.
- When tested with a XCode simulator, the app just hangs for a long time and is completely unresponsive.
- When tested on iPhone or iPad, the app (most likely) crashes if an error/exception is thrown and captured by the sentry sdk.

**Comment by lucas-zimerman** [comment]
Thank you for the repro, we will investigate what is going on with the crash.

**Comment by lucas-zimerman** [comment]
I would recommend using the integration `SentryVue.vueIntegration()` in order to automatically capture the unhandled errors.
Another point is you need to move your errorHandler before initializing sentry, this way it will use the Sentry internal handler added by the vue integration and it will also call your error handler.

Lastly, when using the error handler with the Vue integration you no longer need to capture the error inside your errorHandler.

In regard to the crash, there are two issues on your errorHandler.
1 -  it shouldn't be `async`.
2 -  you should cover your console logs with a try catch block since they can throw errors, and if they throw an error, they will end up on an endless loop locked calling `errorHandler`.

On a similar snippet I managed to record the error that happened on the console log, this way the app no longer hangs
![Image](https://github.com/user-attachments/assets/2440cf80-c04b-425b-b621-b76087326bec)
```typescript

vueApp.config.errorHandler = (error, vm, info) => {
  try{
    console.error(`Unhandled error catched by global error handler
      err: ${error}
      vm: ${vm}
      info: ${info}`);
    }
    catch (err){
      Sentry.captureException(err);
  }
}; 
```

**Comment by chris-si** [comment]
Thanks for the input! I wasn't aware of the possibility of such an endless loop in the global error handler.

It seems to work with the changes you suggested, even though I first still had some troubles on android (now that #689 is resolved) but I'll observe how it behaves in the coming days and if there might be another issue I'll report that in a new issue and close this for now.
